# CONTINUE - Criação de exceção com continue numa combinação de decisão e repetição

for numero in range(1, 11):
    if numero == 5:
        continue
    else:
        print(numero)
print('Laço encerrado')